call createOne.cmd WKP_AltTabR AltTab_Replacer
call createOne.cmd WKP_AsLINUX Move_Windows
call createOne.cmd WKP_CCbyESC Close_Console_by_Escape
call createOne.cmd WKP_Enabler Enable_Disabled_items
call createOne.cmd WKP_IconsFont Desktop_Icons_Font
call createOne.cmd WKP_ISCROLL Scroll_Windows
call createOne.cmd WKP_RClickcp Expand_Paste_menus
call createOne.cmd WKP_SizeWnd Change_Size
call createOne.cmd WKP_SoundCtr Constrol_Sound_Card
call createOne.cmd WKP_SpellCheck Check_Spelling
call createOne.cmd WKP_TextScr Text_extractor
call createOne.cmd WKP_TimeSync Sync_Current_time
call createOne.cmd WKP_UselessStart Put_CPU_on_Start
call createOne.cmd wkp_megamouse Screen_Magnifier
call createOne.cmd WKP_WinPuncher Window_Puncher 
call createOne.cmd WKP_TypeStats Typing_Statistics