call createOne.cmd NoteSkin_Nihcap5 Nihcap5
call createOne.cmd NoteSkin_Nihcap6 Nihcap6
call createOne.cmd NoteSkin_Nihcap7 Nihcap7
call createOne.cmd NoteSkin_Nihcap8 Nihcap8
call createOne.cmd NoteSkin_ObjectDock ObjectDock

call createOne.cmd NoteSkin_Megavolt Megavolt
call createOne.cmd NoteSkin_MoonPhases MoonPhases
call createOne.cmd NoteSkin_Nihcap2 Nihcap2
call createOne.cmd NoteSkin_Nihcap3 Nihcap3
call createOne.cmd NoteSkin_Nihcap4 Nihcap4
call createOne.cmd NoteSkin_OSX OSX
call createOne.cmd NoteSkin_ProgGeek ProgGeek
call createOne.cmd NoteSkin_Smileys3 Smileys3
call createOne.cmd NoteSkin_LeshiyPlane Plane
call createOne.cmd NoteSkin_LeshiyPainted Painted
call createOne.cmd NoteSkin_LeshiyHelloween Helloween
call createOne.cmd NoteSkin_LeshiyAllInOne AllInOne
call createOne.cmd NoteSkin_Leshiy3D 3D
call createOne.cmd NoteSkin_KDE KDE
call createOne.cmd NoteSkin_Jolie Jolie
call createOne.cmd NoteSkin_Flowers Flowers
call createOne.cmd NoteSkin_Elexelm Elexelm
call createOne.cmd NoteSkin_Elexelm2 Elexelm2
call createOne.cmd NoteSkin_Xakep Xakep
call createOne.cmd NoteSkin_Nirvana Nirvana
call createOne.cmd NoteSkin_BGirls GirlsInBlue
