call createOne.cmd WCT_Anecdote
call createOne.cmd WCT_BelarusWeather
call createOne.cmd WCT_CNNNews
call createOne.cmd WCT_CursorPack
call createOne.cmd WCT_CursorPack2
call createOne.cmd WCT_DeskLife
call createOne.cmd WCT_Gazeta
call createOne.cmd WCT_LangTeacherAR
call createOne.cmd WCT_LangTeacherER
call createOne.cmd WCT_OnlineQuote
call createOne.cmd WCT_Search
call createOne.cmd WCT_TongueTwister
call createOne.cmd WCT_Transition
call createOne.cmd WCT_Transl
call createOne.cmd WCT_TranslE
call createOne.cmd WCT_VideoClip
call createOne.cmd WCT_WebCamera
call createOne.cmd WCT_CalenSkins
call createOne.cmd WCT_Elefun

